# -*- coding: utf-8 -*-
"""PySpark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_6crg_O2JEBPgrPndEfqgsvcBdIzBPA

# **PySpark Assignment**

# Assignment 1
"""

from google.colab import files
files.upload()

!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

from pyspark.sql import SparkSession
from pyspark import SparkContext, SparkConf

# create the session
conf = SparkConf().set("spark.ui.port", "4050")

# create the context
import pyspark
sc = pyspark.SparkContext(conf=conf)
spark = SparkSession.builder.getOrCreate()

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip
get_ipython().system_raw('./ngrok http 4050 &')
!sleep 10
!curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

df = spark.read.csv("heroes_information.csv", header = True)

"""**2. Show only top 10 records.**"""

df.show(10)

"""**3. Find the count of male heroes.**"""

df.createOrReplaceTempView("heroes")
spark.sql("SELECT count(*) from heroes where Gender='Male' ").show()

"""**4. Find the count of Female heroes.**"""

spark.sql("SELECT count(*) from heroes where Race='Female' ").show()

"""**5. Find the count of the particular race**"""

spark.sql("select count(*) as HumanCount from heroes where Race='Human'").show()

"""# Assignment 2

**1. Reading Data from file**
"""

from google.colab import files
files.upload()

"""**2. Schema of Dataframe**"""

df = spark.read.csv("WorldCupPlayers (1).csv", header = True)

df.describe().show()

df.printSchema()

"""**3. count of the number of Rows and Columns of Dataframe.**"""

df.toPandas().shape[0]

df.toPandas().shape[1]

"""**5. Show the records where Match ID must be equal to 1096 and calculate how many records/rows are there in the filtered output.**"""

df.createOrReplaceTempView("players")
spark.sql("select * from Players where MatchID='1096' ").show()

spark.sql("select count(*) from Players where MatchID='1096' ").show()

"""**6. Sort the data by match id**"""

df.sort("MatchID").show()

"""**7. Show the records of position C and event is G40.**"""

df.createOrReplaceTempView("players")
spark.sql("select * from Players where Position='C' or Event='G40' ").show()

"""**8. Show the unique records with respect to match id.**"""

spark.sql("select distinct MatchID from players").show()

"""# Q.3 use olympics.csv file

**1. Load the file**
"""

from google.colab import files
files.upload()

df=spark.read.csv("olympix_data.csv",sep='\t',header=True)

df.show()
df.printSchema()

"""**2. Filter the records of India**"""

df.filter(df.Country=='India').show()

from pyspark.sql.functions import *
df2 = df.withColumn("Total Medals",col("Total Medals").cast("Integer"))
df2.printSchema()

"""**3. Show the final result as country and the total number of medals won by each country in all the Olympic games.**"""

df2.groupBy("Country").sum("Total Medals").show()

"""**4. Display the Athlete name and his country**"""

df.select(col('Athlete'),col('Country')).show()

"""**5.Count the number of records**"""

spark.sql("select count(*) from players").show()

df.createOrReplaceTempView("oly")
spark.sql("select count(*) from oly").show()

"""**6. Show the count of each country in a particular sport.**"""

spark.sql("select count(Country),Sport from oly group by Sport").show()